### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by DearFloyd** [lukasHoel/stylemesh#1]
Is there a pre-trained model？

**Comment by lukasHoel** [comment]
No, since you optimize for a separate texture per scene/style. We provide pre-processed data for an example ScanNet scene though (see Readme), which you can use to optimize your own texture in ~30 min.

You can also check out the project website that features an interactive example textured mesh for another scene/style combination: https://lukashoel.github.io/stylemesh/
